spring:
  datasource:
    # require the test database in ./docker/compose.test.yml is running
    url: jdbc:mariadb://localhost:3306/vocadb_site
    username: vocadb
    password: my_password

logging:
  level:
    mikufan:
      cx:
        songfinder: debug