# this compose file can be used in CI env where it runs the test in very fresh env
# it needs to be used with docker\compose.base.yml

services:
  app:
    container_name: song-finder-vocadb-test-runner
    command: gradle check --scan

  mariadb:
    container_name: song-finder-vocadb-test-mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./import-test-data/:/hoshizora.sql/output/
      - ./import-script/mariadb.sql:/docker-entrypoint-initdb.d/mariadb.sql # we could just use the db files, but this will lose the env var
