version: '3.9'

# the base compose file defining two services: app and mariadb

services:
  app:
    image: song-finder-vocadb-app-build:latest
    build:
      context: ../
      dockerfile: docker/clean-env.Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/vocadb_site
      - SPRING_DATASOURCE_USERNAME=vocadb
      - SPRING_DATASOURCE_PASSWORD=my_password
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    healthcheck:
      # see https://github.com/MariaDB/mariadb-docker/issues/94#issuecomment-1069429616
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 3s
      timeout: 3s
      retries: 30
