# this compose file can be used in CI env where it runs the test in very fresh env

services:
  app:
    container_name: song-finder-vocadb-test-runner
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/vocadb_site
      - SPRING_DATASOURCE_USERNAME=vocadb
      - SPRING_DATASOURCE_PASSWORD=my_password
    command: gradle check --scan

  mariadb:
    container_name: song-finder-vocadb-test-mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./import-test-data/:/hoshizora.sql/output/
      - ./import-script/mariadb.sql:/docker-entrypoint-initdb.d/mariadb.sql
